"use client";

import { useState, useRef, useEffect } from "react";

/* ═══════════════════════════════════════════
   ICONS
   ═══════════════════════════════════════════ */

const SparkleIcon = ({ className = "w-4 h-4" }: { className?: string }) => (
  <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <path d="M12 2l2.4 7.2L22 12l-7.6 2.8L12 22l-2.4-7.2L2 12l7.6-2.8z" fill="currentColor" />
  </svg>
);

const CheckIcon = () => (
  <svg width="18" height="18" viewBox="0 0 20 20" fill="none">
    <path d="M5 10.5l4 4 6.5-7" stroke="#1a1a1a" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

const ChevronDown = ({ className = "" }: { className?: string }) => (
  <svg width="20" height="20" viewBox="0 0 16 16" fill="none" className={className}>
    <path d="M4 6l4 4 4-4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

/* ═══════════════════════════════════════════
   VIDEO CARD (with mute/unmute toggle)
   ═══════════════════════════════════════════ */

let activeVideoId: string | null = null;

function PricingVideoCard({ src, id }: { src: string; id: string }) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [muted, setMuted] = useState(true);

  useEffect(() => {
    const handler = (e: Event) => {
      const detail = (e as CustomEvent).detail;
      if (detail !== id && videoRef.current) {
        videoRef.current.muted = true;
        setMuted(true);
      }
    };
    window.addEventListener("creafy-unmute", handler);
    return () => window.removeEventListener("creafy-unmute", handler);
  }, [id]);

  const toggleMute = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (videoRef.current) {
      const newMuted = !muted;
      if (!newMuted) {
        window.dispatchEvent(new CustomEvent("creafy-unmute", { detail: id }));
      }
      videoRef.current.muted = newMuted;
      setMuted(newMuted);
    }
  };

  return (
    <div
      className="relative rounded-2xl overflow-hidden bg-gray-200 aspect-[9/16] w-[46vw] md:w-[200px] shrink-0 cursor-pointer select-none"
      onClick={toggleMute}
      role="button"
      tabIndex={0}
    >
      <video
        ref={videoRef}
        src={src}
        autoPlay
        loop
        muted
        playsInline
        className="absolute inset-0 w-full h-full object-cover"
        style={{ pointerEvents: "none" }}
      />
      {/* Mute/Unmute indicator — Apple-style glass */}
      <div
        className="absolute top-3 right-3 w-9 h-9 bg-white/20 backdrop-blur-xl border border-white/30 rounded-full flex items-center justify-center z-10 transition-all shadow-lg pointer-events-none"
      >
        {muted ? (
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
            <path d="M11 5L6 9H2v6h4l5 4V5z" fill="white" fillOpacity="0.85" />
            <path d="M16 9.5L21 14.5" stroke="white" strokeWidth="2" strokeLinecap="round" />
            <path d="M21 9.5L16 14.5" stroke="white" strokeWidth="2" strokeLinecap="round" />
          </svg>
        ) : (
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
            <path d="M11 5L6 9H2v6h4l5 4V5z" fill="white" fillOpacity="0.85" />
            <path d="M15.54 8.46a5 5 0 010 7.07" stroke="white" strokeWidth="2" strokeLinecap="round" />
            <path d="M19.07 4.93a10 10 0 010 14.14" stroke="white" strokeWidth="2" strokeLinecap="round" />
          </svg>
        )}
      </div>
    </div>
  );
}

/* ═══════════════════════════════════════════
   SCROLLING VIDEO ROWS
   ═══════════════════════════════════════════ */

function VideoShowcase() {
  const row1Videos = ["/price1.mp4", "/price2.mp4", "/price3.mp4", "/price4.mp4", "/price5.mp4"];
  const row2Videos = ["/price6.mp4", "/price7.mp4", "/price8.mp4", "/price9.mp4", "/price10.mp4"];

  return (
    <section className="py-16 bg-[#F6F6F8] overflow-hidden">
      {/* Row 1 — scrolls left */}
      <div className="mb-4 overflow-hidden">
        <div className="flex gap-4 animate-scroll-left-slow" style={{ width: "max-content" }}>
          {[...row1Videos, ...row1Videos].map((src, i) => (
            <PricingVideoCard key={`r1-${i}`} src={src} id={`r1-${i}`} />
          ))}
        </div>
      </div>
      {/* Row 2 — scrolls right */}
      <div className="overflow-hidden">
        <div className="flex gap-4 animate-scroll-right-slow" style={{ width: "max-content" }}>
          {[...row2Videos, ...row2Videos].map((src, i) => (
            <PricingVideoCard key={`r2-${i}`} src={src} id={`r2-${i}`} />
          ))}
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════
   FAQ ACCORDION
   ═══════════════════════════════════════════ */

const faqData = [
  {
    q: "Can I see a demo?",
    a: "Yes! Check out the sample videos on this page — they were all generated by Creafy in under 2 minutes. What you see is what you get.",
  },
  {
    q: "Can I use the videos for commercial purposes?",
    a: "Absolutely. All videos generated with Creafy are fully licensed for commercial use, including paid advertising on any platform.",
  },
  {
    q: "Can I cancel anytime or get a refund?",
    a: "Yes, you can cancel your subscription at any time with no questions asked. If you're not satisfied within the first 7 days, we'll give you a full refund.",
  },
  {
    q: "Can AI hold my product?",
    a: "Yes! Our AI actors can hold and interact with your product. Just upload a photo of your product and the AI will naturally incorporate it into the video.",
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="border-b border-gray-200 last:border-b-0">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between py-5 text-left"
      >
        <span className="text-[16px] md:text-[18px] font-semibold text-[#1a1a1a]">{q}</span>
        <ChevronDown className={`transition-transform duration-200 text-[#888] shrink-0 ml-4 ${open ? "rotate-180" : ""}`} />
      </button>
      {open && (
        <p className="pb-5 text-[15px] text-[#666] leading-relaxed">{a}</p>
      )}
    </div>
  );
}

/* ═══════════════════════════════════════════
   TOP NAV
   ═══════════════════════════════════════════ */

function TopNav() {
  return (
    <nav className="pt-6 pb-4 bg-[#F6F6F8]">
      <div className="container-main flex items-center justify-between">
        <a href="/" className="flex items-center gap-2 text-[22px] font-extrabold text-[#1a1a1a] tracking-tight no-underline">
          <span className="w-9 h-9 bg-[#1a1a1a] rounded-lg flex items-center justify-center text-white text-[20px] font-extrabold">C</span>
          creafy
        </a>
        <a href="#" className="text-[14px] font-medium text-[#555] hover:text-[#1a1a1a] transition-colors no-underline">Log in</a>
      </div>
    </nav>
  );
}

/* ═══════════════════════════════════════════
   PRICING PAGE
   ═══════════════════════════════════════════ */

export default function PricingPage() {
  return (
    <main>
      <TopNav />

      {/* Hero — Simple Pricing */}
      <section className="pt-8 md:pt-14 pb-14 bg-[#F6F6F8]">
        <div className="container-main text-center">
          <h1 className="text-[36px] md:text-[52px] lg:text-[60px] font-extrabold text-[#1a1a1a] leading-[1.1] mb-4 tracking-tight">
            Simple pricing
          </h1>
          <p className="text-[18px] md:text-[22px] text-[#888] mb-12">
            One plan. Everything included.
          </p>

          {/* Pricing Card */}
          <div className="max-w-sm mx-auto bg-white rounded-3xl shadow-lg border border-gray-100 overflow-hidden">
            {/* Price header */}
            <div className="px-7 pt-7 pb-5 text-center border-b border-gray-200">
              <div className="flex items-baseline justify-center gap-1">
                <span className="text-[48px] md:text-[56px] font-extrabold text-[#1a1a1a] leading-none">$39</span>
                <span className="text-[18px] text-[#999] font-medium">/mo</span>
              </div>
            </div>

            {/* Features list */}
            <div className="px-7 py-6">
              <ul className="space-y-3.5 text-left">
                {[
                  "20 video ads per month",
                  "Delivered in 2 minutes",
                  "Up to 120 second videos",
                  "300+ realistic AI actors",
                  "Create your own actor",
                  "No watermark",
                  "35+ languages available",
                ].map((feat, i) => (
                  <li key={i} className="flex items-center gap-3">
                    <CheckIcon />
                    <span className="text-[15px] md:text-[16px] text-[#333]">{feat}</span>
                  </li>
                ))}
              </ul>

              {/* Extra videos note */}
              <p className="mt-5 text-[13px] text-[#999] text-center">
                Need more? Additional videos at <span className="font-semibold text-[#666]">$1.90 each</span>.
              </p>

              {/* CTA */}
              <a href="https://buy.stripe.com/7sYaEY5oCgoG1c5eqtes000" className="inline-flex items-center gap-2 btn-dark w-full justify-center mt-5 text-[16px] py-4">
                <SparkleIcon className="w-4 h-4" />
                Create your first ad
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* Video Showcase */}
      <VideoShowcase />

      {/* Trusted by brands */}
      <section className="py-16 bg-[#F6F6F8]">
        <div className="container-main text-center">
          <h2 className="text-[22px] md:text-[28px] font-bold text-[#1a1a1a] mb-8">
            Trusted by 300+ brands making <span className="text-[#5C7DEE]">$100M+</span> in sales
          </h2>
          <div className="max-w-3xl mx-auto">
            <img
              src="/empresas.png"
              alt="Trusted brands"
              className="w-full h-auto"
            />
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-16 bg-[#F6F6F8]">
        <div className="container-main">
          <h2 className="text-[28px] md:text-[38px] font-extrabold text-[#1a1a1a] text-center mb-10 tracking-tight">
            Frequently Asked Questions
          </h2>
          <div className="max-w-2xl mx-auto bg-white rounded-2xl px-6 md:px-8 border border-gray-100 shadow-sm">
            {faqData.map((faq, i) => (
              <FAQItem key={i} q={faq.q} a={faq.a} />
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
